LineaLabs/lineapy

lineapy/graph_reader/apis.py, tests/unit/graph_reader/test_artifact_get_code.py
only removes the line if all references to lineapy.xxxx were removed. We do not currently handle any other cases but lineapy.save(xxx) and lineapy.get(xxx).value
Fixes LIN-346
extended existing unit tests
=> LIN-346 fix the very narrow case of removing "import lineapy"

lineapy/db/db.py
Fix sqlite locked while multiple notebook running at same time by adding a `renew_session` after writing to sqlite(only).
LIN-349
* Locally spin up two jupyter notebooks (one endless writing and one reading) with sqlite backend, without locking.
=> LIN-349 Add renew_session for sqlite connection

lineapy/__init__.py, tests/outputs/expected/sliced_housing_multiple_requirements.txt, tests/outputs/expected/sliced_housing_multiple_w_dependencies_requirements.txt, tests/outputs/expected/sliced_housing_simple_requirements.txt
Bumps to 0.0.5 to release the `.get_value()` API.
Bug fix (non-breaking change which fixes an issue)
PyPi tested in prod.
=> version bump

docs/source/index.rst
Some notebooks had been renamed but the corresponding indexing has not, so they do not show up in Sphinx.
Bug fix (non-breaking change which fixes an issue)
No testing needed for docs
=> Update page indexing in Sphinx to display renamed tutorial notebook

.gitmodules, lineapy/cli/cli.py, lineapy/external.annotations.yaml, tests/end_to_end/test_pandas.py, tests/integration/__snapshots__/test_slice/test_slice[pandas_apply].py, tests/integration/__snapshots__/test_slice/test_slice[pandas_deleting].py, tests/integration/__snapshots__/test_slice/test_slice[pandas_filtering].py, tests/integration/__snapshots__/test_slice/test_slice[pandas_merge].py, tests/integration/__snapshots__/test_slice/test_slice[pandas_stats].py, tests/integration/__snapshots__/test_slice/test_slice[pandas_timeseries].py, tests/integration/slices/pandas_apply.py, tests/integration/slices/pandas_deleting.py, tests/integration/slices/pandas_filtering.py, tests/integration/slices/pandas_merge.py, tests/integration/slices/pandas_stats.py, tests/integration/slices/pandas_timeseries.py, tests/integration/test_slice.py
Add integration tests with pandas examples, and annotations.
LIN-184
* Add integration tests for `pandas`.
Using notebooks in [pandas_exerciese](https://github.com/guipsamora/pandas_exercises). (BSD-3) as source. We are not using in official pandas repository because they are in `.rst` format.
* New annotations.
Found lineapy works in following assign pattern
```
iris1['petal_length'].fillna(1, inplace=True)
```
but not works in following
```
iris2.petal_length.fillna(1, inplace=True)
iris3.iloc[10:30,2:3] = 1
iris4.loc[iris4.petal_length.isnull(),['petal_length']]=1
iris5.at[10:29,'petal_length']=1
```
Need another ticket for this.
* Integration tests for examples
* New end_to_end tests for new annotations.
=> Lin 184 test pandas examples

.gitmodules, tests/integration/__snapshots__/test_slice/test_slice[sklearn_compose_plot_feature_union].py, tests/integration/__snapshots__/test_slice/test_slice[sklearn_mixture_plot_concentration_prior].py, tests/integration/__snapshots__/test_slice/test_slice[sklearn_model_selection_plot_randomized_search].py, tests/integration/__snapshots__/test_slice/test_slice[sklearn_multioutput_plot_classifier_chain_yeast].py, tests/integration/__snapshots__/test_slice/test_slice[sklearn_preprocessing_plot_scaling_importance].py, tests/integration/__snapshots__/test_slice/test_slice[sklearn_semi_supervised_plot_label_propagation_structure].py, tests/integration/__snapshots__/test_slice/test_slice[sklearn_tree_plot_cost_complexity_pruning].py, tests/integration/slices/sklearn_compose_plot_feature_union.py, tests/integration/slices/sklearn_mixture_plot_concentration_prior.py, tests/integration/slices/sklearn_model_selection_plot_randomized_search.py, tests/integration/slices/sklearn_multioutput_plot_classifier_chain_yeast.py, tests/integration/slices/sklearn_preprocessing_plot_scaling_importance.py, tests/integration/slices/sklearn_semi_supervised_plot_label_propagation_structure.py, tests/integration/slices/sklearn_tree_plot_cost_complexity_pruning.py, tests/integration/test_slice.py
Add integration test for `scikit-learn`. 
For `sklearn.base.BaseEstimator.fit_transform` method and classes within `sklearn.model_selection`. The original estimator does not mutate. `sklearn` is actually only copying the parameters. Thus, no need for new annotations. 
LIN-382
Local integration tests.
=> Lin 382 add annotations for sklearn

docs/source/guide/build_pipelines/index.rst, docs/source/guide/manage_artifacts/database/postgres.rst, docs/source/support/faq.rst, lineapy/utils/config.py
We made our package public using the name lineapy. Making sure the reference to the .linea folder gets updated to reflect the name.
Fixes LIN-390
=> LIN-390 - rename the .linea folder to .lineapy

README.md, docs/source/fundamentals/interfaces.rst
Update docs for usage in different flavors of notebooks. Add a section `Hosted Jupyter Environment` for that.
LIN-397
Docs
Sphinx docs have been tested locally.
=> Lin 397 docs add documentation on the flavors of notebooks linea py works with

docs/source/references/internals.rst
Fix broken existing links in RTD and clean up markdown style broken links.
LIN-357
Local doc build, verify no '](' exists and verify links are working.
=> LIN-357 rtd markdown link cleanup

lineapy/db/db.py, lineapy/plugins/base.py, lineapy/utils/analytics/__init__.py
This change is to address the warning that `DISTINCT ON` query may not work in non-Postgres backends. So we just query the fields we need and then apply `DISTINCT` without `ON` params.
CI will kick in.
=> Refactor a function to address warning (future error)

lineapy/system_tracing/_function_calls_to_object_side_effects.py, tests/end_to_end/test_blackbox_tracing.py
Added a sample code that fails to execute. Lineapy should not stop execution of usercode even if tracing is not possible. This PR adds an escape if the __self__ attribute is missing. Also added a failing test highlighting where the inside-blackbox tracing is not working.
Fixes LIN-417
Added a test_blackbox_tracing.py. It still fails but the execution does not halt (fails because the slice is wrong)
=> LIN-417 fix blackbox trace error

tests/test_script.py
If tests were cancelled midway through previously, attempt to clean up mess when running next time.
LIN 371
Bugfix
The current suite of unit tests pass.
=> Clean up custom-annotations folder when testing annotations commands

tests/integration/test_slice.py
Fixed dependencies used for running Pytorch integration tests. The test would not run completely due to bad versioning. Note the test still fails, but runs till completion.
Fixes # LIN-373
=> Fixing pytorch dependencies for integration tests

README.md
* Fix `Use Case 2: Revisiting Previous Work` demo notebook on Google Colab.
* Directly open GitHub demo notebooks from Google Colab, no more accidentally change.
* Add *Open in Colab* option for each use case in README.md.
* The api_basic notebook and three use cases notebook has been merged in https://github.com/LineaLabs/demos .
LIN-435
Manually click on the link and run demo notebooks in Colab.
=> LIN-435 Fix broken Colab demo notebook

tests/end_to_end/test_linea_api.py
Two reasons causing these two xfail test cases.
* When we called res.values['x']. I think it is actually asking the tracer to return the last value of x but not the last version of x in the artifact store.
* ExecuteFixture actually executes the code twice in the test(i don't know why). I think it should be once. This is why you see cannot delete version 1 error.
Two xfail in test_linea_api.py
=> Fix xfail in test_linea_api.py

lineapy/system_tracing/exec_and_record_function_calls.py
Problem: Currently, the vscode debugger behaves incorrectly whenever the user code has a function definition within it. As soon as a CallNode which deals with a function definition is encountered, when the vscode debugging is in progress, the vscode debugger would ignore the subsequent breakpoints and the program would complete, making subsequent debugging difficult.
Cause: When we call settrace(None), we end up inadvertently disabling all tracers currently set, even vscode's tracer, which causes debugger's unexpected behavior.
Solution: instead of using settrace(None), we store the original tracer and and use settrace(original_tracer), which preserves the original vscode's tracer used for debugging.
Fixes # 
=> Fixing settrace call

lineapy/utils/analytics/usage_tracking.py, lineapy/utils/config.py
To better understand usage patterns, include runtime env info env info (Colab, IPython, etc.) in existing usage reporting. Specifically, with this update, LineaPy differentiates and records two types of runtime env:
1. `non-ipython`
2. IPython-based, e.g.:
- `<IPython.terminal.interactiveshell.TerminalInteractiveShell at 0x10511f1c0>`
- `<ipykernel.zmqshell.ZMQInteractiveShell object at 0x1075df4c0>`
- `<google.colab._shell.Shell object at 0x7ff79b1d1250>`
This information can be overridden by setting environmental variable `LINEAPY_RUNTIME` to the desired value (e.g., `sangyoon_demo`), which would help us to filter out usage traffic coming from internal dev work.
Locally tested with simple examples; CI will kick in.
=> LIN-427 Include runtime info in usage reporting

.gitmodules
Changes submodules to https endpoints to remove the requirement for
public key authentication to install lineapy from source in environments
that do not have GitHub ssh authentication enabled.
- [x ] Bug fix (non-breaking change which fixes an issue)
Tested locally in a Docker environment.
```
docker run -it --rm python
pip install git+https://github.com/hogepodge/lineapy.git@fix-submodules --upgrade
```
=> Change submodules to https endpoints

docs/source/tutorials/04a_adding_library_annotations.ipynb, docs/source/tutorials/04b_adding_custom_annotations.ipynb, docs/source/tutorials/custom_annotations-usercode.ipynb, examples/tutorials/04a_adding_library_annotations.ipynb, examples/tutorials/04b_adding_custom_annotations.ipynb, examples/tutorials/custom_annotations-usercode.ipynb, examples/tutorials/myclass.py, examples/tutorials/sample_user_class.py, lineapy/__init__.py, lineapy/api/api.py, lineapy/execution/executor.py, lineapy/execution/inspect_function.py
Currently if we add new annotations when a (jupyter/ipython) session has started, the new annotations do not show up. This PR adds a reload api that will re-read the annotations. Ideally we'd create an api that lets us replicate the cli options like MJL's config PR. Leaving that out of scope for this PR so we can merge the new feature in.
Fixes LIN-415
New notebook called custom-annotations-usercode.ipynb highlights and tests the feature.
=> Reload annotations

lineapy/utils/analytics/usage_tracking.py, lineapy/utils/config.py
Our API call counts in Amplitude are skewed by the number of API calls in demo/tutorial notebooks. To have a better reflection of organic usage, we want to discard calls from any demo/tutorial notebooks. We can achieve this by having a line at top:
```python
lineapy.options.set("is_demo", True)
```
which flags the notebook as a demo run and use this info to turn off usage report.
We are doing this instead of
```python
%env LINEAPY_DO_NOT_TRACK=true
```
because the latter may give the new user an impression that the command is a necessary setup, in which case they will copy it in their own notebook sessions by default (which we do not want).
***NOTE:*** This PR does NOT update existing demo/tutorial notebooks because the new config option is not yet part of PyPI release, so it will result …
=> LIN-452 Add a config option to flag demo

lineapy/system_tracing/_trace_func.py, tests/unit/system_tracing/test_exec_and_record_function_calls.py
Running
```python
if None is not None:
pass
```
in 3.8 and below crashes the interpreter.
The issue was in the function tracer, where `is not` was missing from the `COMPARE_OPS` registry. This bug doesn't appear in 3.9+, because `is not` was separated out of the `COMPARE_OP` bytecode instruction.
Added unit test to `test_exec_and_record_function_calls.py`.
=> LIN-457 `is not` is not functional under LineaPy

HISTORY.md, lineapy/api/api.py, lineapy/data/types.py, lineapy/db/relational.py, lineapy/instrumentation/tracer.py, lineapy/utils/utils.py
When the user uses artifacts saved from other sessions, they need to pay attention to the Python version compatibility. For instance, artifacts created and saved under an older version of Python may generate errors due to syntax deprecation. Our preference is to *warn* the user about this version incompatibility but NOT interrupt the workflow.
This update involves change in ORM, so it demands DB migration to work with previously created LineaPy DB, which is open as a separate ticket (i.e., [LIN-381](https://linea.atlassian.net/browse/LIN-381)).
Locally tested through virtual environments running different Python versions.
=> LIN-439 Check Python version compatibility when retrieving an artifact

lineapy/data/types.py, lineapy/db/db.py, lineapy/db/relational.py, lineapy/instrumentation/tracer.py, tests/end_to_end/test_variable.py
* Save session variable assignment to `assigned_variable_node` table
* Add class method to read variable assignment by `node_id` or `session` as following
``` python
db.db.get_variable_by_id(self, linea_id: LineaID) -> List[str]
db.db.get_variables_for_session(self, session_id: LineaID) -> List[Tuple[LineaID, str]]
```
If we go with this approach, (LIN-428) doesn't require database migration (LIN-381)
LIN-459
Add new test and pass all existing tests
=> LIN-459 save graph variable name information

lineapy/instrumentation/tracer.py, tests/end_to_end/test_import.py, tests/end_to_end/test_variable.py
Found an error while running 
```
import pandas as pd
import pandas as pd
```
because we try to write the same (node_id, variable_name) to the database again. 
This happens when we try to import the same thing twice, we are using the same node.
LIN-459
New test added
=> Fix error when import same module twice

.gitignore
In [CONTRIBUTING.md](https://github.com/LineaLabs/lineapy/blob/main/CONTRIBUTING.md), I was instructed to create "lineapy" as the folder name for virtualenv. An alternative solution would be updating the folder name (from lineapy to venv) in CONTRIBUTING.md.
Tested locally in venv
=> Update .gitignore for contributors who use venv 

lineapy/cli/cli.py
Summary:
This commit adds a '-v' and '--version' flags to Lineapy CLI.
These options print the package name and version when supplied.
Test Plan:
Local testing.
> (linea-venv-3.9.0) Lineas-MacBook-Pro:~ andrewcui$ lineapy -v
> lineapy 0.1.4
> (linea-venv-3.9.0) Lineas-MacBook-Pro:~ andrewcui$ lineapy --version
> lineapy 0.1.4
JIRA:
LIN-483
=> LIN-483 Add version options to lineapy cli

setup.py
Fix LIN-496
`Inspector.has_table` doesn't exist until version 1.4.
(note: on versions below 1.4 we could use `Engine.has_table` instead)
=> Pin SQLAlchemy to at least v1.4

lineapy/editors/ipython.py, tests/test_ipython.py
When using IPython, add `import lineapy` to the result of `artifact.get_code()` if the artifact contains a lineapy call.
Because lineapy is loaded as an extension when using ipython, `import lineapy` is not needed. However, the line still needs to be added into the code of an artifact so it does not break when the user attempts to re-executes the artifact in a non-IPython environment.
361
`test_lineapy_import_included_in_artifact` added in `test_ipython.py`
=> Lin 361 Missing lineapy import in IPython

.pre-commit-config.yaml, lineapy/cli/cli.py, lineapy/editors/ipython.py, lineapy/transformer/node_transformer.py, lineapy/transformer/transform_code.py, pyproject.toml, requirements.txt, tests/conftest.py, tests/tools/requirements_txt_gen.py, tests/unit/transformer/test_node_transformer.py, tests/unit/transformer/test_transform_code.py
This was done when preparing for another design task. Looks like a helpful change since we had transform function sitting inside nodetransformer module.
Fixes N/A
- [ x ] This change requires a documentation update
existing tests
=> move transform function into its own module.

lineapy/db/db.py, lineapy/utils/config.py
Two oneliner bug fixes were found during workshop/demo prep.
1. When running `import pandas as pd` twice, it will get an error because it tries to write to the table with the same records and break the unique (variable_name, node_id) constraint.
2. Sometimes we get an error related to no access to `fsspec.implementations.local.LocalFileSystem` when we configure s3 as the artifact storage backend. Since `fsspec.implementations.local.LocalFileSystem` is not public facing, need to import separately. 
Hotfix
Pass existing tests
=> Oneline bug fix

lineapy/_alembic/env.py, lineapy/cli/cli.py, lineapy/utils/logging_config.py
Summary:
This commit fixes the --verbose and --logging-level
options for lineapy.
Changes:
1. Fix verbose option by setting correct key in lineapy_config options.set
2. Fix logging level option by implementing logic to set logging level from provided parameter
3. Fix logging by disabling alembic logging override
4. Fix logging by moving off logging.basicConfig, which does not override previously set handler correctly
5. Remove support for logging-level to be set by numbers
6. Changed SQL logging level to match alembic.ini
Test Plan:
Run locally with
lineapy --verbose
lineapy --log-level CRITICAL
lineapy --log-level DEBUG
=> LIN-495 Fix logging and verbosity options

lineapy/plugins/utils.py
In order to reuse slugify from the Django codebase, the copyright
notice must be redistributed as well.
=> Add Django License information

lineapy/api/api.py, tests/conftest.py, tests/test_api.py, tests/test_ipython.py
Make try_write_to_pickle in api.py a private method as it is not meant to be user-facing.
pre-commit checks all passed.
=> Make try_to_write_to_pickle private

lineapy/transformer/transform_code.py
Fix the following error while you run a cell with only comment in Jupyter Notebooks.
The `ast.parse` object is an empty list if there are only comments in the cell. That's why you see 
```
UnboundLocalError: local variable 'last_statement_result' referenced before assignment
```
Quick fix.
Pass all existing tests and validate the result(no error for a comment-only cell) in the Jupyter notebook.
=> Fix error while running a pure comment cell

lineapy/transformer/node_transformer.py
We redid how we handle the ast.starred nodes. There was missing cleanup though. this PR should remove the old visitor.
N/A
N/A
existing tests.
=> clean up older visitor to avoid confusion.

tests/test_script.py
Fix tests/test_script.py::test_config_order which did not reset the environment variables correctly causing multiple following tests to fail.
Adding `clean_lineapy_env_var` line before function resets env variables using `existing_lineapy_env` prevents env variables set from the test from carrying over and affecting subsequent tests. 
Run pytests
=> Fix tests/test_script.py::test_config_order

lineapy/utils/config.py
Fixes connection errors using `storage_options` and `artifact_store_dir` configured to remote directories. 
Changes
- Move `self.storage_options` up in the list of config attributes. This is to guarantee that it is updated before `artifact_store_dir` which requires it as a dependency. This move fixes the issue because Config updates using `self.__dict__` which goes through attributes in order of definition [documented here PEP 520](https://peps.python.org/pep-0520/ ) 
- Add storage option to `fsspec.open` when writing a heartbeat when `artifact_storage_dir` is first specified. This is so that the newly set storage options apply. 
- Fix setting env variables on lineapy config `set` for `storage_options` and loading from env variables to serialize the storage options to string correctly. …
=> LIN-559 Fix storage_options and artifact_store_dir config update order

lineapy/annotations/external/sklearn.annotations.yaml
Add annotation for `sklearn.BaseEstimator.fit_transform` to fix incorrect sliced result for `pipeline` object in following example
```
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
data = pd.DataFrame({"a": ["a", "a", "A"], "b": ["b", "BB", "B"]})   # ignored before new annotation
pipeline = Pipeline([("one_hot_cat", OneHotEncoder())])
pipelineddata = pipeline.fit_transform(data)                         # ignored before new annotation
```
Two lines described in the example are missing from the `get_code` if we save `pipeline` as an artifact.
Pass all existing tests.
=> Add annotation for sklearn.BaseEstimator.fit_transform

lineapy/__init__.py, lineapy/utils/analytics/usage_tracking.py, lineapy/utils/version.py, setup.py
This diff fixes the acquiring of lineapy version in `usage_tracking.py`. The original method uses `importlib_metadata` which will error out in cases where the module is no installed but is instead being used from source as a library. This is because the environment will not have lineapy installed and is not discoverable by importlib, but is discoverable as a module in `sys.path`. 
If this is the case, any script calling `import lineapy` will fail with 
```
importlib.metadata.PackageNotFoundError: lineapy
```
This PR fixes the issue by adding a try except to read the version directly from the modules internal `__version__` if lineapy is not installed.
This fix required moving the definition of version to its own file to avoid circular dependency.  
Please delete options that are not …
=> Fix obtaining version in usage_tracking

lineapy/db/db.py, lineapy/plugins/jinja_templates/airflow_dockerfile.jinja, lineapy/plugins/jinja_templates/script_dockerfile.jinja, lineapy/plugins/pipeline_writers.py, tests/unit/plugins/expected/airflow_complex_h_perart/airflow_complex_h_perart_Dockerfile, tests/unit/plugins/expected/airflow_pipeline_a0_b0/airflow_pipeline_a0_b0_Dockerfile, tests/unit/plugins/expected/airflow_pipeline_a0_b0_dependencies/airflow_pipeline_a0_b0_dependencies_Dockerfile, tests/unit/plugins/expected/airflow_pipeline_housing_multiple/airflow_pipeline_housing_multiple_Dockerfile, tests/unit/plugins/expected/airflow_pipeline_housing_multiple/airflow_pipeline_housing_multiple_requirements.txt, tests/unit/plugins/expected/airflow_pipeline_housing_simple/airflow_pipeline_housing_simple_Dockerfile, tests/unit/plugins/expected/airflow_pipeline_housing_simple/airflow_pipeline_housing_simple_requirements.txt, tests/unit/plugins/expected/airflow_pipeline_housing_w_dependencies/airflow_pipeline_housing_w_dependencies_Dockerfile, tests/unit/plugins/expected/airflow_pipeline_housing_w_dependencies/airflow_pipeline_housing_w_dependencies_requirements.txt, tests/unit/plugins/expected/script_pipeline_a0_b0/script_pipeline_a0_b0_Dockerfile, tests/unit/plugins/expected/script_pipeline_a0_b0_dependencies/script_pipeline_a0_b0_dependencies_Dockerfile, tests/unit/plugins/expected/script_pipeline_housing_multiple/script_pipeline_housing_multiple_Dockerfile, tests/unit/plugins/expected/script_pipeline_housing_multiple/script_pipeline_housing_multiple_requirements.txt, tests/unit/plugins/expected/script_pipeline_housing_simple/script_pipeline_housing_simple_Dockerfile, tests/unit/plugins/expected/script_pipeline_housing_simple/script_pipeline_housing_simple_requirements.txt, tests/unit/plugins/expected/script_pipeline_housing_w_dependencies/script_pipeline_housing_w_dependencies_Dockerfile, tests/unit/plugins/expected/script_pipeline_housing_w_dependencies/script_pipeline_housing_w_dependencies_requirements.txt
The CMD command in the script dag Dockerfile was `["standalone"]`, which is apparently not going to work(if you really try to build the docker image) since it is a airflow command. 
LIN-578
Pass all existing tests and local docker build/run success.
=> LIN-578 Fix broken script pipeline Dockerfile

README.md, docs/source/fundamentals/interfaces.rst, lineapy/__main__.py
Add `__main__.py` so that lineapy can be run as a module. 
`python -m lineapy <args>` now works the same as `lineapy python <args>`
Run locally
```
python -m lineapy --help
python -m lineapy --slice "p value" tests/housing.py
```
=> Make Lineapy runnable as python module

lineapy/graph_reader/artifact_collection.py, lineapy/plugins/jinja_templates/module.jinja, pytest.ini, tests/__snapshots__/test_ipython/test_to_airflow_pymodule.py, tests/__snapshots__/test_ipython/test_to_airflow_with_config_pymodule.py, tests/unit/graph_reader/test_artifact_collection.py, tests/unit/plugins/expected/airflow_complex_h_perart/airflow_complex_h_perart_module.py, tests/unit/plugins/expected/airflow_pipeline_a0_b0/airflow_pipeline_a0_b0_module.py, tests/unit/plugins/expected/airflow_pipeline_a0_b0_dependencies/airflow_pipeline_a0_b0_dependencies_module.py, tests/unit/plugins/expected/airflow_pipeline_housing_multiple/airflow_pipeline_housing_multiple_module.py, tests/unit/plugins/expected/airflow_pipeline_housing_simple/airflow_pipeline_housing_simple_module.py, tests/unit/plugins/expected/airflow_pipeline_housing_w_dependencies/airflow_pipeline_housing_w_dependencies_module.py, tests/unit/plugins/expected/script_pipeline_a0_b0/script_pipeline_a0_b0_module.py, tests/unit/plugins/expected/script_pipeline_a0_b0_dependencies/script_pipeline_a0_b0_dependencies_module.py, tests/unit/plugins/expected/script_pipeline_housing_multiple/script_pipeline_housing_multiple_module.py, tests/unit/plugins/expected/script_pipeline_housing_simple/script_pipeline_housing_simple_module.py, tests/unit/plugins/expected/script_pipeline_housing_w_dependencies/script_pipeline_housing_w_dependencies_module.py
Modify the `module.jinja` to wrap with `argparse`  when input parameters are detected. 
LIN-545
- Pass all existing tests(with update some snapshot)
- Execute the output module from cli directly, and validate it produce expected value
=> Lin 545 parameterize the python module for framework script pipeline

lineapy/annotations/external/prophet.annotations.yaml
Add annotations for `prophet`
Only annotate `prophet.Prophet.fit`
LIN-588
Following code(from prophet official website) works
```
%load_ext lineapy
import pandas as pd
from prophet import Prophet
df = pd.read_csv('https://raw.githubusercontent.com/facebook/prophet/main/examples/example_wp_log_peyton_manning.csv')
df.head()
m = Prophet()
m.fit(df)
future = m.make_future_dataframe(periods=365)
future.tail()
forecast = m.predict(future)
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()
art = dict()
art['model'] = lineapy.save(m,'prophet_model')
art['future'] = lineapy.save(future, 'prophet_future')
art['forecast'] = lineapy.save(forecast,'prophet_forecast')
print(art['forecast'].get_code())
```
returns 
```
import pandas …
```
=> LIN-588 Add prophet annotations

lineapy/transformer/node_transformer.py, tests/end_to_end/test_misc.py
When the user attempts to raise an exception, `visit_Raise` raises an attribute error. This
causes the original exception type to be lost.
`test_raises` has been added
=> Fix Exception raising in Lineapy

lineapy/api/api.py, lineapy/api/models/pipeline.py, lineapy/db/relational.py, lineapy/graph_reader/artifact_collection.py, tests/end_to_end/test_linea_api.py
Expose parametrization and artifact reuse to pipeline-related APIs.
Test cases have been added to cover DB schema update.
- [LIN-565](https://linea.atlassian.net/browse/LIN-565)
=> LIN-565 Add parametrization and artifact reuse to pipeline API and DB

lineapy/plugins/jinja_templates/script_dockerfile.jinja, tests/unit/plugins/expected/script_pipeline_a0_b0/script_pipeline_a0_b0_Dockerfile, tests/unit/plugins/expected/script_pipeline_a0_b0_dependencies/script_pipeline_a0_b0_dependencies_Dockerfile, tests/unit/plugins/expected/script_pipeline_housing_multiple/script_pipeline_housing_multiple_Dockerfile, tests/unit/plugins/expected/script_pipeline_housing_simple/script_pipeline_housing_simple_Dockerfile, tests/unit/plugins/expected/script_pipeline_housing_w_dependencies/script_pipeline_housing_w_dependencies_Dockerfile
The existing Dockerfile for `framework='SCRIPT'` does not support passing parameters into `docker run` . Change from `CMD` to `ENTRYPOINT` can resolve this issue easily.
Reference
https://docs.docker.com/engine/reference/builder/#entrypoint
LIN-577
Local docker build/docker run
=> LIN-577 fix parameterized script framework dockerfile

lineapy/graph_reader/session_artifacts.py, tests/test_function.py
Fix `to_pipeline`  and `get_function` errors if multiple artifacts have the same name in a session.
Modify existing test case to cover the scenario
=> Fix error with same artifact name in a session

lineapy/api/api.py, lineapy/api/models/pipeline.py, lineapy/db/relational.py, tests/end_to_end/test_linea_api.py
For better reusability of `Pipeline` objects, use `input_parameters` and `reuse_pre_computed_artifacts` flags in `Pipeline.export()` instead of `Pipeline.__init__()`. This involves unrolling DB schema updates (which have not yet been release yet, so it’s okay!).
CI ensures integrity of the codebase after the edits.
- https://linea.atlassian.net/browse/LIN-597
=> LIN-597 Make `Pipeline.export()` handle parametrization

lineapy/annotations/external/statsforecast.annotations.yaml
The `statsforecast` module has a similar structure to `scikit-learn`. Need to annotate the `_TS` class in `statsforecast.models` to allow lineapy capture the `model.fit` . 
Before adding annotation
```
train = region.query(f"week < '{cutoff_date}'")
m_aa = AutoARIMA()
```
After
```
train = region.query(f"week < '{cutoff_date}'")
m_aa = AutoARIMA()
m_aa.fit(train["log_price"].values)
```
where `AutoARIMA` is a derived class of `_TS` class
=> Add annotation for statsforecast module

lineapy/graph_reader/artifact_collection.py, tests/unit/plugins/expected/airflow_pipeline_two_input_parameter/airflow_pipeline_two_input_parameter_module.py
Originally, the order is based on the appearance of the session code. It is actually not very desirable, especially in multiple sessions cases.
Basically, if we ran
```
lineapy.get_function(['a'], input_parameters=['x','y'])
```
we might get 
```
def run_all_sessions(x, y)
```
or 
```
def run_all_sessions(y, x)
```
depending on the ordering of variable x and y appearance in the session code.
This PR will make it always in the order of the user's input; i.e., 
```
def run_all_sessions(x,y)
```
LIN-611
Update the test result of the existing test case.
The modified existing test case is an example of the user's input does not agree with what the appearance order in the original code, so we need to modify the case.
=> Adjust get_function/to_pipeline input parameter order as user's input.

lineapy/__init__.py, lineapy/utils/analytics/event_schemas.py, lineapy/utils/analytics/usage_tracking.py
But it can be used for tagging other stuff, too.
Introduced a tagging API to track demos.
Logged test events to Amplitude
=> add tagging for demo notebooks

.github/workflows/demos.yml
Address error in https://github.com/LineaLabs/lineapy/actions/runs/3159242653/jobs/5142227673
```
Run cp -R examples/use_cases/* demos/ && cp examples/tutorials/00_api_basics.ipynb demos/
cp -R examples/use_cases/* demos/ && cp examples/tutorials/00_api_basics.ipynb demos/
shell: /usr/bin/bash -e {0}
cp: target 'demos/' is not a directory
Error: Process completed with exit code 1.
```
=> Add mkdir step before cp

.colab/create_a_simple_pipeline/create_a_simple_pipeline.ipynb, examples/use_cases/create_a_simple_pipeline/create_a_simple_pipeline.ipynb, lineapy/plugins/jinja_templates/module_test.jinja, lineapy/plugins/pipeline_writers.py, tests/unit/plugins/expected/script_pipeline_a0_b0_dependencies/test_script_pipeline_a0_b0_dependencies.py, tests/unit/plugins/expected/script_pipeline_housing_w_dependencies/test_script_pipeline_housing_w_dependencies.py, tests/unit/plugins/test_writer.py
As a first story of the `Enable Pipeline Testing` epic, this PR implements a bare minimal scaffolding for pipeline testing, where:
- Each function in the module gets a corresponding test case
- Each test case simply calls the tested function within a try-catch block
- Comments are provided to instruct the user to adjust test logic as needed
Though very simple, this bare minimal templating may still deliver some value to the user as it provides them a starting point for pipeline testing (better to have something than nothing). Again, this is a first story for the epic, and the plan is to improve on it with subsequent stories.
Unit tests were added to cover the new functionality.
- [LIN-579](https://linea.atlassian.net/browse/LIN-579)
=> LIN-579 Provide user with pipeline test skeleton

lineapy/graph_reader/session_artifacts.py, lineapy/plugins/pipeline_writers.py, tests/unit/plugins/expected/airflow_complex_h_perart/airflow_complex_h_perart_requirements.txt, tests/unit/plugins/expected/airflow_pipeline_a0_b0/airflow_pipeline_a0_b0_requirements.txt, tests/unit/plugins/expected/airflow_pipeline_a0_b0_dependencies/airflow_pipeline_a0_b0_dependencies_requirements.txt, tests/unit/plugins/expected/airflow_pipeline_a_b0_inputpar/airflow_pipeline_a_b0_inputpar_requirements.txt, tests/unit/plugins/expected/airflow_pipeline_a_b0_inputpar_session/airflow_pipeline_a_b0_inputpar_session_requirements.txt, tests/unit/plugins/expected/airflow_pipeline_housing_multiple/airflow_pipeline_housing_multiple_requirements.txt, tests/unit/plugins/expected/airflow_pipeline_housing_simple/airflow_pipeline_housing_simple_requirements.txt, tests/unit/plugins/expected/airflow_pipeline_housing_w_dependencies/airflow_pipeline_housing_w_dependencies_requirements.txt, tests/unit/plugins/expected/airflow_pipeline_two_input_parameter/airflow_pipeline_two_input_parameter_requirements.txt, tests/unit/plugins/expected/script_pipeline_a0_b0/script_pipeline_a0_b0_requirements.txt, tests/unit/plugins/expected/script_pipeline_a0_b0_dependencies/script_pipeline_a0_b0_dependencies_requirements.txt, tests/unit/plugins/expected/script_pipeline_housing_multiple/script_pipeline_housing_multiple_requirements.txt, tests/unit/plugins/expected/script_pipeline_housing_simple/script_pipeline_housing_simple_requirements.txt, tests/unit/plugins/expected/script_pipeline_housing_w_dependencies/script_pipeline_housing_w_dependencies_requirements.txt
Currently, the requirements.txt is generated from the entire session graph(s if multiple sessions). This is more than the pipeline need. 
This is fixed by giving session artifacts a `get_libraries` method. This will go through and match session libraries with import_nodes that form the ImportNodeCollection to ensure that libraries not in the slice are not included.
Fixes LIN-619
- [ X ] Bug fix (non-breaking change which fixes an issue)
`tests/unit/plugins/expected/<framework>_pipeline_housing * .ipynb` test cases contain examples where the 
Specifically in these examples `lineapy`, `seaborn` and `altair` were libraries only used during EDA and not actually needed for the artifact.
=> LIN-619 Fix imports in requirements.txt

lineapy/graph_reader/artifact_collection.py, lineapy/graph_reader/session_artifacts.py, tests/test_function.py
Better error handling of the following cases. 
- A parameter is missing from the resulting modules. 
- A variable is defined as a literal more than once within a slice. 
- A variable has _only_ non literal assignments. 
Error messages should contain the parameter in question.
Last case of only non literal assignments fixed. The old error message was unreachable. 
Tests updated to check the error message.
Fixes # LIN-628
- [ X ] Bug fix (non-breaking change which fixes an issue)
`test_function` has been updated to check the error message being returned in each case as well.
=> LIN-628: Fix error handling around input_parameter variable

lineapy/graph_reader/artifact_collection.py, lineapy/graph_reader/node_collection.py, lineapy/graph_reader/session_artifacts.py, tests/test_function.py
Continue the work in https://github.com/LineaLabs/lineapy/pull/808.
* Separate warnings for input parameters with dependent variables and non-primitive input parameters.
* Fix error in following code
```
x = 1
x = x+1
lineapy.save(x, 'x')
ft = lineapy.get_function(['x'], input_parameters=['x'])
ft(1) 
```
This is due to the input parameter being incorrect in the artifact calculation function definition
LIN-628
Existing test + new tests
=> LIN-628 fix-error-handling-around-input-params-plut-function-def

lineapy/api/api.py, lineapy/api/models/pipeline.py, lineapy/cli/cli.py, lineapy/graph_reader/artifact_collection.py, lineapy/graph_reader/session_artifacts.py, lineapy/plugins/loader.py, lineapy/plugins/pipeline_writers.py, tests/unit/graph_reader/test_artifact_collection.py, tests/unit/plugins/test_writer.py
Refactor internal Artifact Collection class.
- Move `_compose_module` to BasePipelineWriter, since it does not modify the Artifact Collection but returns a string representation that can be parametrized which is more suitable for Writer classes.
- `generate_module_text` refactored out. Sorting session artifacts is now done in constructor and prettify is in `_compose_modules`. All external references replaced with `_compose_module`. 
- Move `get_module`, which requires a written version of the module to a utility function and rename to `load_as_module` in `lineapy.plugins.loader`. Since the desired use case is to run a function/module, this should be replaced by proper execution of a module through the LineaGraph in the future. 
- Cleanup constructor for ArtifactCollection. Grouping …
=> LIN-656, LIN-640: Refactor Artifact Collection

lineapy/api/api.py, lineapy/api/models/linea_artifact.py, lineapy/api/models/pipeline.py, lineapy/graph_reader/artifact_collection.py, lineapy/graph_reader/node_collection.py, lineapy/graph_reader/program_slice.py, lineapy/graph_reader/session_artifacts.py, tests/unit/graph_reader/test_program_slice.py
With the goal of letting users edit the sliced code that made it to the pipeline, we decided that it's easiest if we include the sliced-away bits so that the user can easily add the parts that they want to keep. This adds a cleanup step for them but will be more flexible til we add more magic and fine-tune what the user needs.
Fixes LIN-533
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] This change requires a documentation update
existing tests, pending adding new tests if required.
=> LIN-533 keep unsliced code

lineapy/api/models/pipeline.py, lineapy/graph_reader/artifact_collection.py, lineapy/graph_reader/node_collection.py, lineapy/graph_reader/session_artifacts.py, lineapy/plugins/pipeline_writers.py, lineapy/plugins/session_writers.py, tests/unit/graph_reader/test_artifact_collection.py, tests/unit/graph_reader/test_node_collection.py
Refactor NodeCollection, breaking up single NodeCollection class and NodeCollectionType Enum into 
distinct classes with inheritance. 
Changes
- Breaks up NodeCollection into subclasses. BaseNodeCollection, which has subclasses UserCodeNodeCollection, ImportNodeCollection and InputVarNodeCollection.  UserCodeNodeCollection has a subclass for ArtifactNodeCollection. Artifact collections coming from re-use precomputed are unchanged, and defined by `is_pre_computed_artifact`.
- Remove unused parameters from these NodeCollections. For  ImportNodeCollection and InputVarNodeCollection, only a node_list inherited from BaseNodeCollection is necessary. 
- Remove `module_import`, `predecessor_artifact`, `sliced_nodes` and other unneeded parameters from dataclass. 
- Moved …
=> LIN-640, LIN-667, Refactor NodeCollection and _slice_session_artifacts

README.md
README currently includes non-working link for installation from the source code (because the link points to contributor guide which is not yet in `main`). Until the dev branch (`LIN-680-produce-first-revamp-of-contributor-guide`) is merged to `main`, use a temporary working link (pointing to dev branch).
NA
NA
=> [Hotfix] Use working link to dev branch until it is merged to main

lineapy/transformer/base_transformer.py, lineapy/transformer/conditional_transformer.py, lineapy/transformer/node_transformer.py, lineapy/transformer/py37_transformer.py, lineapy/transformer/py38_transformer.py, lineapy/transformer/transform_code.py, lineapy/utils/deprecation_utils.py, tests/unit/transformer/test_node_transformer.py, tests/unit/transformer/test_transform_code.py
This PR moves the code to handle changes in ast over different python versions to their own transforms. this way nodetransformer remains agnostic of the version and makes future additions plug-n-playable.
Fixes LIN-560
- [ x ] New feature (non-breaking change which adds functionality)
existing test + some modified unit tests
=> LIN-560 separate nodetransformers

docs/source/guide/manage_artifacts/storage_location/postgres.rst, requirements.txt, setup.py, tests/tools/requirements_txt_gen.py
Change instructions to use psycopg2-binary
Fixes #839 
Reinstalled lineapy in a new venv from setup
``pip install -r requirements.txt `` and ensure no errors and that DB connection works.
=> Change instructions to use psycopg2-binary

setup.py
Pin SQLAlchemy<2.0.0. 
Lineapy install doesnt work with the latest version of sqlalchemy library (>= 2.0.0)
[https://docs.sqlalchemy.org/en/20/intro.html
](https://docs.sqlalchemy.org/en/20/intro.html)
[https://sqlalche.me/e/20/zlpr](https://sqlalche.me/e/20/zlpr)
```
sqlalchemy.exc.ArgumentError: Type annotation for "ArtifactORM.node" can't be correctly interpreted for Annotated 
Declarative Table form.  ORM annotations should normally make use of the ``Mapped[]`` generic type, or other ORM-
compatible generic type, as a container for the actual type, which indicates the intent that the attribute is mapped. Class 
variables that are not intended to be mapped by the ORM should use ClassVar[].  To allow Annotated Declarative to 
disregard legacy annotations which don't use Mapped[] to …
```
=> Pin SQLAlchemy<2.0.0

airflow-requirements.txt, lineapy/plugins/base_pipeline_writer.py
when output_dir="~", it should point to the user's home directory instead of the relative path that it resolves to right now.
existing tests should not create a ~ folder in the project root or in tests/notebooks
=> Fix resolution of ~ in output_dir

lineapy/api/api_utils.py, lineapy/api/artifact_serializer.py, lineapy/api/models/linea_artifact.py, requirements.txt, setup.py, tests/tools/requirements_txt_gen.py
Start using cloudpickle. In general, cloudpickle supports more use cases but specifically it works around the constraint of the pickle class that requires class objects to be registered in globals().  This will let linea keep hijacking the default globals and work with a separate copy in executor.
Fixes LIN-712
- [ x ] New feature (non-breaking change which adds functionality)
All existing tests.
=> LIN-712 use cloudpickle

lineapy/utils/analytics/usage_tracking.py, tests/unit/utils/test_usage_tracking.py
This PR adds properties that ties a user's session to the events we see in amplitude. This will help us trace the user journeys much better and get feedback on which features are popular or where exceptions occur for a user.
Fixes LIN-729
- [ x ] New feature (non-breaking change which adds functionality)
new test added
=> LIN-729 add new user properties in every request

lineapy/data/types.py, lineapy/plugins/airflow_pipeline_writer.py, lineapy/plugins/jinja_templates/airflow_dockerfile.jinja, lineapy/plugins/jinja_templates/kubeflow_dag.jinja, lineapy/plugins/jinja_templates/kubeflow_dockerfile.jinja, lineapy/plugins/jinja_templates/script_dockerfile.jinja, lineapy/plugins/jinja_templates/task/parameterizedpickle/task_parameterized_deser.jinja, lineapy/plugins/jinja_templates/task/parameterizedpickle/task_parameterized_ser.jinja, lineapy/plugins/jinja_templates/task/task_function.jinja, lineapy/plugins/kubeflow_pipeline_writer.py, lineapy/plugins/pipeline_writer_factory.py, lineapy/plugins/task.py, lineapy/plugins/taskgen.py, tests/unit/plugins/__snapshots__/test_writer.ambr, tests/unit/plugins/test_writer.py
Adds support for kubeflow pipelines. Setting `framework= KUBEFLOW` in `to_pipeline` now produces a dag file that can be run through the kubeflow pipeline sdk. 
Also adds task serialization that can be parametrized so that the save location can be specific through the task function signature. Kubeflow's `get_rendered_task_definitions` uses this by adding these locations as function parameters to `user_input_variables`. 
Fixes LIN-724
Using housing example on local kubeflow setup.
=> LIN-724: Kubeflow Integration

lineapy/utils/analytics/usage_tracking.py, lineapy/utils/config.py, tests/unit/utils/test_usage_tracking.py
persist device id so that we dont keep getting new random numbers (a situation that can happen with uuid.getnode())
Fixes LIN-729
New test added to ensure that device id gets persisted to the lineapy folder.
=> LIN-729 persist device ids.

requirements.txt, setup.py
Pin the version of typing-extensions >= 4.0.0
This is so that the user does not run into issue when installing lineapy out of the box. 
Version 4.0.0 was chosen on typing-extensions' release logs 
[which indicate 4.0.0 was the version where typing_extensions.NotRequired was added]. (https://github.com/python/typing_extensions/blob/673e5ceea32f77d90531d4d5e77a7694edba7fba/CHANGELOG.md)
Tested locally on a python 3.8 env
=> LIN-735: Pin typing-extensions >= 4.0.0 for NotRequired type hint

lineapy/plugins/argo_pipeline_writer.py, lineapy/plugins/jinja_templates/argo_dag.jinja, lineapy/plugins/jinja_templates/argo_dockerfile.jinja, lineapy/plugins/jinja_templates/kubeflow_dockerfile.jinja, tests/unit/plugins/__snapshots__/test_writer.ambr
Argo tests at this time snapshot the user home directory, which means the snapshot tests must be manually updated to pass on github actions.
This PR moves the path expansion to the dag file itself, meaning the generated DAG will not depend on the users home directory. 
Also added and fixed hints for how to use the Dockerfile for argo. 
Fixes LIN-737
Tested locally with housing example, both providing and not providing a kube config
`        "kube_config": "/Users/andrewcui/.kube/config",`
=> LIN-737: Fix argo tests requiring /home/runner

tests/conftest.py, tests/test_mlflow.py, tests/unit/utils/test_config_mlflow.py
Some MLflow tests require setting some configuration flags using  which are not reset by default, which leads to subsequent tests failing due to unexpected configuration. Hence, for such tests, we reset the  as well as the env variables to tackle the bug.
Fixes # (LIN-740)
Tested locally using `pytest`
=> LIN-740: Reset configurations

lineapy/plugins/airflow_pipeline_writer.py, lineapy/plugins/argo_pipeline_writer.py, lineapy/plugins/dvc_pipeline_writer.py, lineapy/plugins/kubeflow_pipeline_writer.py, lineapy/plugins/ray_pipeline_writer.py, lineapy/plugins/task.py, lineapy/plugins/taskgen.py, tests/unit/plugins/framework_specific/airflow/__snapshots__/test_writer_airflow.ambr
Consolidate get_rendered_task_definitions to helper function in task.py
* Add `render_task_definitions` helper function which takes in generator functions for each code block (or else takes defaults) and renders the task template including generating the `task_serialization` block. 
* Change all pipeline integration frameworks to use this.
Fixes LIN-734
Assert that snapshot tests did not change. 
(Airflow tests have their tasks re-organized in a different order due the removal of a sort, but the file generated is still the same,
=> LIN-734 Consolidate Getting Rendered Tasks

.colab/01_using_artifacts.ipynb, README.md, docs/mkdocs/tutorials/01_using_artifacts.ipynb, examples/tutorials/01_using_artifacts.ipynb, lineapy/api/api.py, lineapy/api/models/pipeline.py, tests/notebook/test_airflow.ipynb, tests/test_ipython.py
Make `to_pipeline` return `Pipeline` object
Fix existing `to_pipeline` related tests that rely on the `output_dif` and pass all of them.
=> Platform 618 to pipeline returns pipeline object
