README.md
docs/source/fundamentals/interfaces.rst
docs/source/fundamentals/quickstart.rst
docs/source/fundamentals/setup.rst

Add documentation on how to load lineapy as an extension in an existing Jupyter application.
Testing is not required for doc update.

LIN-365 Add documentation on how to load lineapy as an extension in an existing Jupyter application

---

docs/source/conf.py

Embed JS script to Sphinx docs to enable usage reporting on Crazy Egg
- New feature (non-breaking change which adds functionality)
This is an update for docs, so it does not require testing.

LIN-376 Embed JS script to enable usage reporting on Crazy Egg

---

README.md

Add a Colab button to API basics tutorial for new users to get the first feel of LineaPy right away.
No testing needed.

LIN-383 Add a Colab button for API basics tutorial

---

docs/source/fundamentals/setup.rst

Describe how `lineapy` work with `JupyterHub`
Documentation change
LIN-355
Doc
NA

LIN-355 Update JupyterHub info in setup.rst

---

docs/source/tutorials/00_api_basics.ipynb
examples/tutorials/00_api_basics.ipynb

Integrate user feedback for API basics tutorial. Updates include:
- Section reordering (introduce `catalog()` before `get()`)
- Adaptation of narrative to suit this reordering
- Discussion of some output file from `to_pipeline()`
- Addition of Colab link
CI will kick in to test the notebook code.

LIN-404 Revamp API basics tutorial

---

README.md

Fix outdated links for story-based demos.
No testing needed.

Fix outdated demo links

---

docs/source/autogen/lineapy.exceptions.rst
docs/source/autogen/lineapy.graph_reader.rst
lineapy/__init__.py
lineapy/api/api.py
lineapy/db/db.py
lineapy/plugins/base.py
lineapy/plugins/utils.py
tests/outputs/expected/sliced_housing_multiple_requirements.txt
tests/outputs/expected/sliced_housing_multiple_w_dependencies_requirements.txt
tests/outputs/expected/sliced_housing_simple_requirements.txt

Version bump and doc build update.
Release!
Verified that local pip install on built wheel is working.

bump version and update docs

---

README.md

Embed LineaPy intro video in README.
Doc update; no testing needed.

Embed video in readme

---

lineapy/db/db.py

Explicitly check to see if version is not None.
Bug fix (non-breaking change which fixes an issue)

Remove type coercion in get_artifact_by_name

---

README.md

Add Binder Link for demo notebooks.
Have another PR https://github.com/LineaLabs/demos/pull/14 for these notebooks.
LIN-424
Manually test all links are pointing to the right location

Add Binder link for demos

---

.github/workflows/docs.yml

This action was failing when merge or rebase on a brach that already has the copy step executed. The git commit step fails if there are no changes. adding a check to see if there are changes and only if there are will be proceed to commit.
Fixes N/A
not tested

fix the pesky error that keeps appearing when we merge or rebase

---

lineapy/api/api.py
lineapy/api/api_classes.py
lineapy/db/db.py
lineapy/execution/context.py
lineapy/utils/analytics/event_schemas.py
lineapy/utils/analytics/usage_tracking.py

Improve exception tracking/report. Changes include:
- Use of enums for tracked exception types
- Some new exceptions being tracked/reported
- More concise error message for tracking/report
This update does not affect code behavior, so no need for testing; CI will kick in regardless.

LIN-434 Improve exception tracking/report

---

docs/source/tutorials/00_api_basics.ipynb
docs/source/tutorials/01_refactor_code.ipynb
docs/source/tutorials/02_build_pipelines.ipynb
docs/source/tutorials/04a_adding_library_annotations.ipynb
docs/source/tutorials/04b_adding_custom_annotations.ipynb
examples/tutorials/00_api_basics.ipynb
examples/tutorials/01_refactor_code.ipynb
examples/tutorials/02_build_pipelines.ipynb
examples/tutorials/04a_adding_library_annotations.ipynb
examples/tutorials/04b_adding_custom_annotations.ipynb
examples/use_cases/predict_house_price/01_preprocessing.ipynb
examples/use_cases/predict_house_price/02_modeling.ipynb
examples/use_cases/predict_house_price/03_pipelining.ipynb

This is a followup task from #697: now that the change has been published in a new PyPI release, we want to actually update demo/tutorial notebooks accordingly.
CI will test notebooks, but expecting no surprise.

LIN-455 Set `is_demo` option in all demo notebooks

---

CONTRIBUTING.md

This update clarifies how contributions to the LineaPy community,
and in particular pull requests to the LineaPy repository works.
It states the roles and responsibilities of code maintainers
is approving pull requests and requesting changes to pull requests.
Contributor documentation update
Not required

LIN-544 Update Contributor Guide

---

.github/workflows/demos.yml
pytest.ini

Fix NBVAL does not properly clean up in demos notebook

Lin 621 cleanup nbval prefix

---

demos/00_api_basics.ipynb
demos/clean_up_a_messy_notebook/clean_up_a_messy_notebook.ipynb
demos/create_a_simple_pipeline/create_a_simple_pipeline.ipynb
demos/discover_and_trace_past_work/discover_and_trace_past_work.ipynb
demos/predict_house_price/housing_example.ipynb
examples/use_cases/discover_and_trace_past_work/discover_and_trace_past_work.ipynb

Need to trigger demo copy to demos 

Modify a comment to trigger demo copy

---

lineapy/api/models/pipeline.py

example of how i think we should clear the path for contributors by removing anything we dont expect them to touch into private functions.
Fixes N/A
Pure refactor
existing tests

pipeline export refactor to simplify code navigation for contributors

---

tests/test_pipeline_run_airflow.py

Original test only ran `airflow dag run` which does not check the dag runs successfully, now add check for `airflow dag state` to be success after a while. 
Run test with failing DAG, ensure test fails.

Fix test_pipeline_run_airflow test

---

docs/source/development/areas/integrate_pipeline_framework.rst
docs/source/guide/build_pipelines/index.rst
lineapy/plugins/task.py

Create a step-by-step tutorial for integrating a new pipeline framework
Fixes: LIN-696

[LIN-696] Add pipeline integration tutorial

---

lineapy/graph_reader/artifact_collection.py
lineapy/graph_reader/session_artifacts.py
lineapy/graph_reader/utils.py

Refactoring artifact collection's get_artifacts_grouped_by_session. This PR functions more as a sample than a functional refactoring.
Existing tests

minor refactoring to allow for unit testing

---

.github/workflows/airflow.yml
.github/workflows/argo.yml
.github/workflows/deploy-image.yml
.github/workflows/dvc.yml
.github/workflows/kubeflow.yml
.github/workflows/python-app.yml
.github/workflows/ray.yml
.github/workflows/sync_notebooks.yml

Add dispatch options to Lineapy Tests, which will allow triggering of tests on a branch manually. 
This is done by adding on:workflow_dispatch directive to each action. 
Tested on personal fork.

Add manual dispatch options to Lineapy GithubAction Tests

---

README.md
examples/self-hosting-lineapy/README.md

Fix 2 links

---

.vscode/settings.json
LICENSE.txt

feat: small license change
